# -*- coding: utf-8 -*-
"""Indian Education System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lls1lvzXW8mtVxOu55KkbowZFN1jmHKJ
"""



import pandas as pd
import numpy as np

dropout=pd.read_csv("/dropout_ratio.csv")

dropout.head()

dropout.columns

dropout.shape

dropout.info()

dropout.describe()

dropout.isna()

dropout.isna().count()

dropout.isna().any()

data_wb=dropout[dropout['State_UT']=='West Bengal']

print(data_wb.head())

data_wb.info()

dropout.groupby('State_UT').groups

dropout['Primary_Boys'].values

dropout=dropout.replace('NR',0)

dropout['Primary_Boys'].values

dropout['Primary_Boys']=dropout['Primary_Boys'].apply(lambda x:float(x))

dropout['Upper Primary_Boys'].values

dropout=dropout.replace('Uppe_r_Primary',0)

dropout['Upper Primary_Boys'].values

dropout.dtypes

primary_boys=dropout['Primary_Boys'].values.astype(np.float32)
dropout['Primary_Girls']=dropout['Primary_Girls'].values.astype(np.float32)

dropout['Upper Primary_Boys']=dropout['Upper Primary_Boys'].values.astype(np.float32)
dropout['Upper Primary_Girls']=dropout['Upper Primary_Girls'].values.astype(np.float32)

dropout['Secondary _Boys']=dropout['Secondary _Boys'].values.astype(np.float32)
dropout['Secondary _Girls']=dropout['Secondary _Girls'].values.astype(np.float32)

dropout['HrSecondary_Boys']=dropout['HrSecondary_Boys'].values.astype(np.float32)
dropout['HrSecondary_Girls']=dropout['HrSecondary_Girls'].values.astype(np.float32)

dropout.dtypes

import matplotlib.pyplot as plt
import seaborn as sns

years=data_wb['year'].values;
print(years)

plt.figure(figsize=(35,15))
sns.countplot(dropout['State_UT'])

data_wb.head()

plt.bar(data_wb['Primary_Girls'],data_wb['year'])
plt.xlabel('Primary_Girls')
plt.ylabel('year')
plt.title('Year Basis Primary_Girls Dropout Ratio in West Bengal')
plt.show()

plt.bar(dropout['Primary_Boys'],dropout['year'])
plt.xlabel('Primary_Boys')
plt.ylabel('year')
plt.title('Year Basis Primary Boys Ratio')
plt.show()

plt.bar(data_wb['Upper Primary_Girls'],data_wb['year'])
plt.xlabel('Upper Primary_Girls')
plt.ylabel('year')
plt.title('Upper Primary_Girls Ratio Vs Year')
plt.show()

plt.hist(dropout['HrSecondary_Girls'])

plt.figure(figsize=(20,15))
plt.subplot(4,4,1)
sns.boxplot(dropout['HrSecondary_Girls'])

plt.subplot(4,4,2)
sns.boxplot(dropout['HrSecondary_Boys'])

plt.subplot(4,4,3)
sns.boxplot(dropout['Upper Primary_Boys'])

plt.subplot(4,4,4)
sns.boxplot(dropout['Upper Primary_Girls'])

plt.subplot(4,4,5)
sns.boxplot(dropout['Secondary _Girls'])

plt.subplot(4,4,6)
sns.boxplot(dropout['Secondary _Boys'])

dropout['HrSecondary_Girls']=dropout['HrSecondary_Girls'].clip(lower=dropout['HrSecondary_Girls'].
quantile (0.05), upper=dropout['HrSecondary_Girls']). quantile(0.95)

dropout['HrSecondary_Boys']=dropout['HrSecondary_Boys'].clip(lower=dropout['HrSecondary_Boys'].
quantile (0.05), upper=dropout['HrSecondary_Boys']). quantile(0.95)

dropout['Upper Primary_Boys']=dropout['Upper Primary_Boys'].clip(lower=dropout['Upper Primary_Boys'].
quantile (0.05), upper=dropout['Upper Primary_Boys']). quantile(0.95)

dropout['Upper Primary_Girls']=dropout['Upper Primary_Girls'].clip(lower=dropout['Upper Primary_Girls'].
quantile (0.05), upper=dropout['Upper Primary_Girls']). quantile(0.95)

dropout['Secondary _Girls']=dropout['Secondary _Girls'].clip(lower=dropout['Secondary _Girls'].
quantile (0.05), upper=dropout['Secondary _Girls']). quantile(0.95)

dropout['Secondary _Boys']=dropout['Secondary _Boys'].clip(lower=dropout['Secondary _Boys'].
quantile (0.05), upper=dropout['Secondary _Boys']). quantile(0.95)

plt.figure(figsize=(20,15))
plt.subplot(4,4,1)
sns.boxplot(dropout['HrSecondary_Girls'])

plt.subplot(4,4,2)
sns.boxplot(dropout['HrSecondary_Boys'])

plt.subplot(4,4,3)
sns.boxplot(dropout['Upper Primary_Boys'])

plt.subplot(4,4,4)
sns.boxplot(dropout['Upper Primary_Girls'])

plt.subplot(4,4,5)
sns.boxplot(dropout['Secondary _Girls'])

plt.subplot(4,4,6)
sns.boxplot(dropout['Secondary _Boys'])





